In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df  = pd.read_csv('shopping_trends.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [4]:
df.isna().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [18]:
# Define age group bins and labels
#age_bins = [0, 17, 25, 35, 45, 60, 100]  # Adjust ranges as needed
age_labels = ['Under 18', '18-25', '26-35', '36-45', '46-60', '60+']
#df['Age Group'] = pd.cut(df['Age'], labels=age_labels, right=False)

In [19]:
# Create a new column for age groups
#df['Age Group'] = pd.cut(df['Age'], labels=age_labels, right=False)

# Group by 'Age Group' and 'Category' and count occurrences
grouped_data = df.groupby(['Age', 'Category']).size().reset_index(name='Count')

# Display the grouped data
print(grouped_data)

     Age     Category  Count
0     18  Accessories     18
1     18     Clothing     33
2     18     Footwear      8
3     18    Outerwear     10
4     19  Accessories     25
..   ...          ...    ...
207   69    Outerwear      5
208   70  Accessories     25
209   70     Clothing     26
210   70     Footwear     12
211   70    Outerwear      4

[212 rows x 3 columns]

In [22]:
# Define custom age groups
age_groups = {
    '18-25': range(18, 26),
    '26-35': range(26, 36),
    '36-45': range(36, 46),
    '46-55': range(46, 56),
    '56-65': range(56, 66),
}

# Assign age groups manually
def assign_age_group(age):
    for group, age_range in age_groups.items():
        if age in age_range:
            return group
    return '60+'

df['Age Group'] = df['Age'].apply(assign_age_group)

# Group by age groups and categories
grouped_data = df.groupby(['Age Group', 'Category']).size().reset_index(name='Count')

print(grouped_data)

   Age Group     Category  Count
0      18-25  Accessories    172
1      18-25     Clothing    269
2      18-25     Footwear     79
3      18-25    Outerwear     51
4      26-35  Accessories    243
5      26-35     Clothing    337
6      26-35     Footwear    108
7      26-35    Outerwear     54
8      36-45  Accessories    249
9      36-45     Clothing    319
10     36-45     Footwear    102
11     36-45    Outerwear     59
12     46-55  Accessories    217
13     46-55     Clothing    321
14     46-55     Footwear    150
15     46-55    Outerwear     65
16     56-65  Accessories    239
17     56-65     Clothing    329
18     56-65     Footwear    114
19     56-65    Outerwear     68
20       60+  Accessories    120
21       60+     Clothing    162
22       60+     Footwear     46
23       60+    Outerwear     27

In [15]:
age_groups

{'18-25': range(18, 26),
 '26-35': range(26, 36),
 '36-45': range(36, 46),
 '46-55': range(46, 56),
 '56-65': range(56, 66)}

In [42]:
# Manually assigning age groups based on conditions without using a loop
#df['Age Group'] = pd.cut(df['Age'], bins=[18, 25, 35, 45, 55, 65, 100], labels=['18-25', '26-35', '36-45', '46-55', '56-65', '60+'], right=False)

# Group by age groups and categories, then count occurrences
grouped_data = df.groupby(['Gender', 'Frequency of Purchases']).size().reset_index(name='Count')

# Display the grouped data
print(grouped_data)

    Gender Frequency of Purchases  Count
0   Female               Annually    185
1   Female              Bi-Weekly    188
2   Female         Every 3 Months    186
3   Female            Fortnightly    163
4   Female                Monthly    185
5   Female              Quarterly    169
6   Female                 Weekly    172
7     Male               Annually    387
8     Male              Bi-Weekly    359
9     Male         Every 3 Months    398
10    Male            Fortnightly    379
11    Male                Monthly    368
12    Male              Quarterly    394
13    Male                 Weekly    367

In [32]:
data=df.groupby(['Gender', 'Item Purchased']).size().reset_index(name='Count')
data

    Gender Item Purchased  Count
0   Female       Backpack     37
1   Female           Belt     55
2   Female         Blouse     66
3   Female          Boots     50
4   Female           Coat     47
5   Female          Dress     52
6   Female         Gloves     37
7   Female        Handbag     58
8   Female            Hat     52
9   Female         Hoodie     51
10  Female         Jacket     54
11  Female          Jeans     29
12  Female        Jewelry     52
13  Female          Pants     48
14  Female        Sandals     59
15  Female          Scarf     45
16  Female          Shirt     59
17  Female          Shoes     48
18  Female         Shorts     48
19  Female          Skirt     49
20  Female       Sneakers     42
21  Female          Socks     58
22  Female     Sunglasses     56
23  Female        Sweater     50
24  Female        T-shirt     46
25    Male       Backpack    106
26    Male           Belt    106
27    Male         Blouse    105
28    Male          Boots     94
29    Male           Coat    114
30    Male          Dress    114
31    Male         Gloves    103
32    Male        Handbag     95
33    Male            Hat    102
34    Male         Hoodie    100
35    Male         Jacket    109
36    Male          Jeans     95
37    Male        Jewelry    119
38    Male          Pants    123
39    Male        Sandals    101
40    Male          Scarf    112
41    Male          Shirt    110
42    Male          Shoes    102
43    Male         Shorts    109
44    Male          Skirt    109
45    Male       Sneakers    103
46    Male          Socks    101
47    Male     Sunglasses    105
48    Male        Sweater    114
49    Male        T-shirt    101

In [39]:
# Count purchases by Category and Item
category_counts = df['Category'].value_counts()
item_counts = df.groupby(['Category']).size().reset_index(name='Count')
item_counts

      Category  Count
0  Accessories   1240
1     Clothing   1737
2     Footwear    599
3    Outerwear    324

In [40]:
df["Category"].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [46]:
category_counts = df['Category'].value_counts()
season_counts = df.groupby(['Season','Category']).size().reset_index(name='Count')
season_counts

    Season     Category  Count
0     Fall  Accessories    324
1     Fall     Clothing    427
2     Fall     Footwear    136
3     Fall    Outerwear     88
4   Spring  Accessories    301
5   Spring     Clothing    454
6   Spring     Footwear    163
7   Spring    Outerwear     81
8   Summer  Accessories    312
9   Summer     Clothing    408
10  Summer     Footwear    160
11  Summer    Outerwear     75
12  Winter  Accessories    303
13  Winter     Clothing    448
14  Winter     Footwear    140
15  Winter    Outerwear     80

In [47]:
df['Location'].unique()

array(['Kentucky', 'Maine', 'Massachusetts', 'Rhode Island', 'Oregon',
       'Wyoming', 'Montana', 'Louisiana', 'West Virginia', 'Missouri',
       'Arkansas', 'Hawaii', 'Delaware', 'New Hampshire', 'New York',
       'Alabama', 'Mississippi', 'North Carolina', 'California',
       'Oklahoma', 'Florida', 'Texas', 'Nevada', 'Kansas', 'Colorado',
       'North Dakota', 'Illinois', 'Indiana', 'Arizona', 'Alaska',
       'Tennessee', 'Ohio', 'New Jersey', 'Maryland', 'Vermont',
       'New Mexico', 'South Carolina', 'Idaho', 'Pennsylvania',
       'Connecticut', 'Utah', 'Virginia', 'Georgia', 'Nebraska', 'Iowa',
       'South Dakota', 'Minnesota', 'Washington', 'Wisconsin', 'Michigan'],
      dtype=object)

In [50]:
map_data = df.groupby(['Location','Category']).size().reset_index(name='Count')
map_data

      Location     Category  Count
0      Alabama  Accessories     25
1      Alabama     Clothing     41
2      Alabama     Footwear     15
3      Alabama    Outerwear      8
4       Alaska  Accessories     26
..         ...          ...    ...
195  Wisconsin    Outerwear      3
196    Wyoming  Accessories     23
197    Wyoming     Clothing     31
198    Wyoming     Footwear     11
199    Wyoming    Outerwear      6

[200 rows x 3 columns]

In [52]:
import chart
print(dir(chart))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'bar', 'histogram', 'preprocessing', 'scatter']

In [57]:
frequency_by_gender = df.groupby("Gender")["Frequency of Purchases"].value_counts().unstack(fill_value=0)
frequency_by_gender

Frequency of Purchases,Annually,Bi-Weekly,Every 3 Months,Fortnightly,Monthly,Quarterly,Weekly
Gender,,,,,,,
Female,185,188,186,163,185,169,172
Male,387,359,398,379,368,394,367

In [63]:
frequency_by_gender.reset_index()

Frequency of Purchases,Gender,Annually,Bi-Weekly,Every 3 Months,Fortnightly,Monthly,Quarterly,Weekly
0,Female,185,188,186,163,185,169,172
1,Male,387,359,398,379,368,394,367

In [60]:
#Top Categories Purchased in Each Season
top_categories_by_season = df.groupby(["Season", "Category"]).size().reset_index(name="Count")
top_categories_by_season

    Season     Category  Count
0     Fall  Accessories    324
1     Fall     Clothing    427
2     Fall     Footwear    136
3     Fall    Outerwear     88
4   Spring  Accessories    301
5   Spring     Clothing    454
6   Spring     Footwear    163
7   Spring    Outerwear     81
8   Summer  Accessories    312
9   Summer     Clothing    408
10  Summer     Footwear    160
11  Summer    Outerwear     75
12  Winter  Accessories    303
13  Winter     Clothing    448
14  Winter     Footwear    140
15  Winter    Outerwear     80

In [72]:
top_categories = top_categories_by_season.groupby("Season").apply(lambda x: x.nlargest(3, "Count")).reset_index(drop=True)
top_categories

C:\Users\akole\AppData\Local\Temp\ipykernel_25440\2040639587.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_categories = top_categories_by_season.groupby("Season").apply(lambda x: x.nlargest(3, "Count")).reset_index(drop=True)

    Season     Category  Count
0     Fall     Clothing    427
1     Fall  Accessories    324
2     Fall     Footwear    136
3   Spring     Clothing    454
4   Spring  Accessories    301
5   Spring     Footwear    163
6   Summer     Clothing    408
7   Summer  Accessories    312
8   Summer     Footwear    160
9   Winter     Clothing    448
10  Winter  Accessories    303
11  Winter     Footwear    140

In [65]:
popular_categories_by_location = df.groupby(["Location", "Category"]).size().reset_index(name="Count")
popular_categories_by_location

      Location     Category  Count
0      Alabama  Accessories     25
1      Alabama     Clothing     41
2      Alabama     Footwear     15
3      Alabama    Outerwear      8
4       Alaska  Accessories     26
..         ...          ...    ...
195  Wisconsin    Outerwear      3
196    Wyoming  Accessories     23
197    Wyoming     Clothing     31
198    Wyoming     Footwear     11
199    Wyoming    Outerwear      6

[200 rows x 3 columns]

In [66]:
popular_categories_map = popular_categories_by_location.sort_values("Count", ascending=False)
popular_categories_map

         Location   Category  Count
17     California   Clothing     47
49       Illinois   Clothing     46
101       Montana   Clothing     45
69      Louisiana   Clothing     44
177       Vermont   Clothing     43
..            ...        ...    ...
139          Ohio  Outerwear      3
195     Wisconsin  Outerwear      3
71      Louisiana  Outerwear      2
155  Rhode Island  Outerwear      2
39        Georgia  Outerwear      1

[200 rows x 3 columns]

In [70]:
map_data = df.groupby(['Location','Category']).size().reset_index(name='Count')
map_data

      Location     Category  Count
0      Alabama  Accessories     25
1      Alabama     Clothing     41
2      Alabama     Footwear     15
3      Alabama    Outerwear      8
4       Alaska  Accessories     26
..         ...          ...    ...
195  Wisconsin    Outerwear      3
196    Wyoming  Accessories     23
197    Wyoming     Clothing     31
198    Wyoming     Footwear     11
199    Wyoming    Outerwear      6

[200 rows x 3 columns]

In [12]:
top_categories = top_categories_by_season.groupby("Season", group_keys=False).apply(lambda x: x.nlargest(3, "Count")).reset_index()
top_categories

NameError: name 'top_categories_by_season' is not defined

In [78]:
top_categories_by_season = df.groupby(["Season", "Category"])["Customer ID"].nunique().unstack(fill_value=0)
top_categories_by_season = top_categories_by_season.reset_index()
top_categories_by_season

Category  Season  Accessories  Clothing  Footwear  Outerwear
0           Fall          324       427       136         88
1         Spring          301       454       163         81
2         Summer          312       408       160         75
3         Winter          303       448       140         80

In [3]:
top_categories_by_season = df.groupby("Season")["Category"].value_counts().unstack(fill_value=0)
top_categories_by_season

Category  Accessories  Clothing  Footwear  Outerwear
Season
Fall              324       427       136         88
Spring            301       454       163         81
Summer            312       408       160         75
Winter            303       448       140         80

In [4]:
#Top Categories Purchased in Each Season
top_categories_by_season = df.groupby(["Season", "Category"]).size().reset_index(name="Count")
top_categories_by_season

    Season     Category  Count
0     Fall  Accessories    324
1     Fall     Clothing    427
2     Fall     Footwear    136
3     Fall    Outerwear     88
4   Spring  Accessories    301
5   Spring     Clothing    454
6   Spring     Footwear    163
7   Spring    Outerwear     81
8   Summer  Accessories    312
9   Summer     Clothing    408
10  Summer     Footwear    160
11  Summer    Outerwear     75
12  Winter  Accessories    303
13  Winter     Clothing    448
14  Winter     Footwear    140
15  Winter    Outerwear     80

In [87]:

top_categories_by_season = df.groupby("Season") ["Category"].value_counts().unstack(fill_value=0)
top_categories_by_season = top_categories_by_season.reset_index()
top_categories_by_season

Category  Season  Accessories  Clothing  Footwear  Outerwear
0           Fall          324       427       136         88
1         Spring          301       454       163         81
2         Summer          312       408       160         75
3         Winter          303       448       140         80

In [93]:
popular_categories_by_location = df.groupby(['Location','Category']).size().reset_index(name='Count')
print(popular_categories_by_location)

      Location     Category  Count
0      Alabama  Accessories     25
1      Alabama     Clothing     41
2      Alabama     Footwear     15
3      Alabama    Outerwear      8
4       Alaska  Accessories     26
..         ...          ...    ...
195  Wisconsin    Outerwear      3
196    Wyoming  Accessories     23
197    Wyoming     Clothing     31
198    Wyoming     Footwear     11
199    Wyoming    Outerwear      6

[200 rows x 3 columns]

In [95]:
frequency_by_gender = df.groupby(["Gender","Frequency of Purchases"]).value_counts().unstack(fill_value=0)
frequency_by_gender

Preferred Payment Method                                                                                                                                                                                                                             Bank Transfer  \
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                               0
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                              0
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                              1
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                              1
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                              0
...                                                                                                                                                                                                                                                            ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                              0
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                               0
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                              0
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                              0
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                               0

Preferred Payment Method                                                                                                                                                                                                                             Cash  \
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                      0
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                     0
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                     0
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                     0
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                     1
...                                                                                                                                                                                                                                                   ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                     0
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                      0
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                     0
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                     0
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                      1

Preferred Payment Method                                                                                                                                                                                                                             Credit Card  \
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                             0
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                            0
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                            0
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                            0
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                            0
...                                                                                                                                                                                                                                                          ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                            0
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                             0
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                            1
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                            1
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                             0

Preferred Payment Method                                                                                                                                                                                                                             Debit Card  \
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                            0
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                           0
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                           0
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                           0
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                           0
...                                                                                                                                                                                                                                                         ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                           1
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                            1
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                           0
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                           0
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                            0

Preferred Payment Method                                                                                                                                                                                                                             PayPal  \
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                        1
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                       0
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                       0
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                       0
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                       0
...                                                                                                                                                                                                                                                     ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                       0
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                        0
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                       0
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                       0
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                        0

Preferred Payment Method                                                                                                                                                                                                                             Venmo
Gender Frequency of Purchases Customer ID Age Item Purchased Category    Purchase Amount (USD) Location       Size Color  Season Review Rating Subscription Status Payment Method Shipping Type Discount Applied Promo Code Used Previous Purchases
Female Annually               2655        23  Coat           Outerwear   70                    Idaho          S    Pink   Fall   4.1           No                  Debit Card     Next Day Air  No               No              4                       0
                              2661        24  Pants          Clothing    85                    South Carolina L    Yellow Spring 4.9           No                  Debit Card     Express       No               No              44                      1
                              2662        43  Boots          Footwear    96                    Michigan       XL   Olive  Fall   4.8           No                  Debit Card     Express       No               No              20                      0
                              2664        46  Sneakers       Footwear    52                    Wisconsin      L    Silver Fall   2.9           No                  Credit Card    Free Shipping No               No              23                      0
                              2673        56  Boots          Footwear    28                    West Virginia  M    Maroon Spring 2.9           No                  Debit Card     Standard      No               No              13                      0
...                                                                                                                                                                                                                                                    ...
Male   Weekly                 2586        57  Sunglasses     Accessories 37                    Wisconsin      L    Maroon Fall   4.4           No                  Venmo          Free Shipping No               No              19                      0
                              2605        47  Sweater        Clothing    54                    Colorado       M    Beige  Spring 3.4           No                  Credit Card    Store Pickup  No               No              6                       0
                              2620        68  Pants          Clothing    40                    Connecticut    L    Indigo Winter 3.9           No                  Credit Card    Free Shipping No               No              47                      0
                              2626        30  Skirt          Clothing    51                    Colorado       L    Cyan   Summer 2.7           No                  Bank Transfer  Standard      No               No              31                      0
                              2632        53  Skirt          Clothing    44                    Connecticut    S    Violet Summer 2.7           No                  PayPal         Express       No               No              3                       0

[3900 rows x 6 columns]

In [7]:
import pandas as pd

data = {'Year': [2022, 2022, 2023, 2023, 2024],
        'Quarter': ['Q1', 'Q2', 'Q1', 'Q2','Q3'],
        'Sales': [100, 120, 150, 180, 210]}
df = pd.DataFrame(data)
print(df)

   Year Quarter  Sales
0  2022      Q1    100
1  2022      Q2    120
2  2023      Q1    150
3  2023      Q2    180
4  2024      Q3    210

In [11]:
df_unstacked = df.set_index(['Year', 'Quarter']).unstack('Quarter', fill_value=0)
print(df_unstacked)

        Sales
Quarter    Q1   Q2   Q3
Year
2022      100  120    0
2023      150  180    0
2024        0    0  210

In [3]:
total_revenue = df['Purchase Amount (USD)'].sum()
print(f'Total revenue: ${total_revenue:.2f}')

Total revenue: $233081.00

In [4]:
total_customers = df['Customer ID'].nunique()
print(f"Total unique customers: {total_customers}")

Total unique customers: 3900

In [4]:
category_growth = df.groupby("Category")["Purchase Amount (USD)"].sum().sort_values(ascending=False)
category_growth.head(3).index.tolist()

['Clothing', 'Accessories', 'Footwear']

In [5]:
location_revenue = df.groupby("Location")["Purchase Amount (USD)"].sum().sort_values(ascending=False)
location_revenue.head(3).index.tolist()

['Montana', 'Illinois', 'California']